import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { HomePage } from './home/home';
import styled from 'styled-components';

const Main = styled.main`
    width: 100vw;
    height: 100vh;
    background-color: #fdfdfd;
    box-sizing: border-box;
`;

export const Home: NextPage = () => {
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Main>
                <HomePage />
            </Main>
            <footer>Foote3r 2x</footer>
        </div>
    );
};

export default Home;
