import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { HomePage } from './home/home';
import styled, { ThemeProvider } from 'styled-components';
import { theme } from './_app';

const Main = styled.main`
    width: 100vw;
    height: 100vh;
    background-color: #fdfdfd;
    box-sizing: border-box;
`;

export const Home: NextPage = () => {
    return (
        <ThemeProvider theme={theme}>
            <div className={styles.container}>
                <Head>
                    <title>Create Next App</title>
                    <meta
                        name="description"
                        content="Generated by create next app"
                    />
                    <link rel="icon" href="/favicon.ico" />
                    <link
                        href="https://fonts.googleapis.com/css2?family=Mulish:wght@200;300;400;500;600;700&display=swap"
                        rel="stylesheet"
                    />
                </Head>
                <Main>
                    <HomePage />
                </Main>
                <footer>Foote3r 2x</footer>
            </div>
        </ThemeProvider>
    );
};

export default Home;
