import type { NextPage } from 'next';
import Head from 'next/head';
import { ThemeProvider } from 'styled-components';
import MainApp from './_app';
import { theme } from '../shared/styles/themes';

export const Home: NextPage = () => {
    return (
        <ThemeProvider theme={theme}>
            {/* TODO: Adicionar tags reais e testar SEO */}
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
                <link
                    href="https://fonts.googleapis.com/css2?family=Mulish:wght@200;300;400;500;600;700&display=swap"
                    rel="stylesheet"
                />
                {/*<link*/}
                {/*    href="https://fonts.googleapis.com/css2?family=Raleway:wght@100;200;300;400;500;600&display=swap"*/}
                {/*    rel="stylesheet"*/}
                {/*/>*/}
            </Head>

            <MainApp />
        </ThemeProvider>
    );
};

export default Home;
